In [10]:
from pyhive import hive
#kerberos
def get_hive_con():
    data_conn = hive.Connection(host='cdh04.irc.com',
                           port=10000,
                           username='station',
                           database='bmnc_stados'
                            , auth='KERBEROS', kerberos_service_name='hive'
                               )
    cur = data_conn.cursor()
    return data_conn,cur

# pd_data1 = pd.read_excel('../../project_abnormal_detect/data/工作日/5分钟粒度.xlsx')

sql="select line_id,substr(station_id,-4) station_id,start_tm,regexp_replace(end_tm,'次日00:00','24:00') end_tm,exit_qtty qtty \
from dos_station_period_st   t where   line_id not in ('82','83','84','85','93','04') and t.start_tm >= '05:00' and t.start_tm<='23:55' \
and start_tm not like '%次日%'   and p_date_scope='20190101-20200905' and p_filter='202002,202003' and p_date_type_cd='1' \
and p_stat_index_type_cd='0060'"

import pandas as pd       
data_conn,cur=get_hive_con()
cur.execute(sql)
data = cur.fetchall()
cols = [i[0] for i in cur.description]
pd_data = pd.DataFrame(data,columns=cols)
pd_data

,line_id,station_id,start_tm,end_tm,qtty
0,01,0103,05:00,06:00,"18,18,25,18,11,28,6,7,15,25,11,14,10,17,18,10,..."
1,01,0103,06:00,07:00,"214,185,183,176,174,132,218,134,174,197,200,15..."
2,01,0103,07:00,08:00,"1042,1044,867,906,676,1030,989,753,955,828,893..."
3,01,0103,08:00,09:00,"1526,1230,897,1745,1623,1401,1761,1446,1864,14..."
4,01,0103,09:00,10:00,"1033,811,1060,925,899,928,812,681,948,709,955,..."
5,01,0103,10:00,11:00,"790,688,825,751,801,816,658,785,787,741,767,70..."
6,01,0103,11:00,12:00,"791,710,761,725,719,744,740,717,700,630,762,73..."
7,01,0103,12:00,13:00,"770,691,685,743,670,711,646,671,641,594,790,69..."
8,01,0103,13:00,14:00,"779,575,605,702,808,744,753,669,748,917,698,70..."
9,01,0103,14:00,15:00,"816,719,714,898,804,823,776,801,965,822,1195,6..."
10,01,0103,15:00,16:00,"975,982,907,955,943,1024,937,1062,1269,1016,11..."
11,01,0103,16:00,17:00,"1467,1355,1507,1311,1384,1452,1401,1532,1260,1..."
12,01,0103,17:00,18:00,"2402,2600,2341,2577,2330,2365,2225,1947,2518,2..."
13,01,0103,18:00,19:00,"3974,3480,3817,3021,4271,3839,3588,3173,2619,4..."
14,01,0103,19:00,20:00,"2756,2516,2915,1915,3058,2336,2657,2784,2464,2..."
15,01,0103,20:00,21:00,"1428,1240,961,1579,1502,1415,1524,1577,1437,13..."
16,01,0103,21:00,22:00,"1290,1306,1378,1319,1107,1270,1020,1476,1194,1..."
17,01,0103,22:00,23:00,"953,837,846,951,940,947,874,802,950,1308,907,9..."
18,01,0103,23:00,24:00,"466,332,339,366,503,370,366,332,387,346,334,37..."
19,01,0104,05:00,06:00,"12,18,5,10,12,9,11,9,10,3,7,4,20,18,18,7,10,9,..."
20,01,0104,06:00,07:00,"183,174,191,199,223,188,172,162,189,214,200,18..."
21,01,0104,07:00,08:00,"1049,970,1030,1105,1235,1045,1039,1087,1130,10..."
22,01,0104,08:00,09:00,"2263,2466,2327,2332,2300,2237,2506,2317,1681,2..."
23,01,0104,09:00,10:00,"1011,1078,1054,1150,1038,1017,1024,1057,1040,1..."
24,01,0104,10:00,11:00,"563,548,586,588,588,612,577,560,520,620,597,59..."
25,01,0104,11:00,12:00,"530,503,496,521,491,598,570,499,529,538,532,54..."
26,01,0104,12:00,13:00,"560,566,552,558,572,623,605,577,552,550,605,59..."
27,01,0104,13:00,14:00,"622,561,652,658,606,630,633,682,542,621,651,64..."
28,01,0104,14:00,15:00,"532,550,567,536,552,647,506,567,542,615,589,58..."
29,01,0104,15:00,16:00,"741,649,753,720,697,700,754,751,718,624,684,71..."
...,...,...,...,...,...
7665,98,9825,13:00,14:00,"496,694,496,538,560,501,444,525,541,541,548,49..."
7666,98,9825,14:00,15:00,"108,190,225,216,526,499,509,583,557,525,535,53..."
7667,98,9825,15:00,16:00,"605,935,573,749,662,1022,612,688,654,867,734,6..."
7668,98,9825,16:00,17:00,"671,709,666,733,800,790,644,570,618,730,753,67..."
7669,98,9825,17:00,18:00,"155,209,185,288,817,808,636,784,627,527,824,65..."
7670,98,9825,18:00,19:00,"709,878,637,876,556,665,830,644,624,623,550,74..."
7671,98,9825,19:00,20:00,"816,899,749,856,958,647,949,1062,1014,696,950,..."
7672,98,9825,20:00,21:00,"114,188,206,355,661,491,515,677,505,487,451,53..."
7673,98,9825,21:00,22:00,"571,332,373,336,289,480,314,427,278,329,285,37..."
7674,98,9825,22:00,23:00,"279,252,281,360,281,305,344,348,280,284,314,24..."
7675,98,9825,23:00,24:00,"8,8,2,13,39,55,22,30,26,64,47,36,36,27,42,63,5..."
7676,98,9827,05:00,06:00,"0,0,0,0"
7677,98,9827,06:00,07:00,"337,323,339,320,255,394,338,377,386,310,380,35..."
7678,98,9827,07:00,08:00,"376,475,652,464,438,556,414,623,544,554,546,39..."
7679,98,9827,08:00,09:00,"294,342,322,279,633,494,581,509,501,519,717,68..."
7680,98,9827,09:00,10:00,"621,628,661,638,701,566,629,614,601,650,746,55..."
7681,98,9827,10:00,11:00,"620,447,540,479,626,548,625,597,562,720,697,46..."
7682,98,9827,11:00,12:00,"411,366,323,378,494,521,561,420,517,461,478,44..."
7683,98,9827,12:00,13:00,"257,555,497,729,600,581,587,592,583,626,650,58..."
7684,98,9827,13:00,14:00,"611,535,602,617,624,609,624,618,509,520,625,59..."
7685,98,9827,14:00,15:00,"150,318,274,348,625,538,668,741,720,560,617,56..."
7686,98,9827,15:00,16:00,"563,614,569,651,554,572,640,530,537,606,583,62..."
7687,98,9827,16:00,17:00,"767,601,716,705,711,682,742,738,698,715,727,69..."
7688,98,9827,17:00,18:00,"360,476,395,650,739,759,700,967,587,683,848,68..."
7689,98,9827,18:00,19:00,"788,881,802,866,996,791,946,1032,1040,720,1752..."
7690,98,9827,19:00,20:00,"713,599,678,623,607,643,617,861,621,790,681,58..."
7691,98,9827,20:00,21:00,"188,203,277,400,444,382,386,388,425,497,332,41..."
7692,98,9827,21:00,22:00,"317,338,334,334,318,300,334,323,402,298,324,30..."
7693,98,9827,22:00,23:00,"262,408,262,334,246,235,321,324,293,259,271,24..."
7694,98,9827,23:00,24:00,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."

In [4]:
import datetime as dt
def get_tomorrow_daytype():
    now = dt.datetime.now()
    compute_date = (now.date()+dt.timedelta(days=1)).strftime("%Y%m%d")    
    print("select holiday_today,work,holiday_rest from bmnc_stados.bmnc_date_prop t where \
                                                        t.date_id='%s'"%compute_date)
    try:
        data_conn,cur = get_hive_con()
        tomorrow_info = pd.read_sql("select holiday_today,work,holiday_rest from bmnc_stados.bmnc_date_prop t where \
                                                            t.date_id='%s'"%compute_date,data_conn)
        cur.close()
        data_conn.close()
    except Exception as e:
        print(e)
        date_prop = pd.read_csv("../date_prop.csv")
        tomorrow_info = date_prop.loc[date_prop['date_id']==int(compute_date)]
        tomorrow_info = tomorrow_info.reset_index()
    
    if tomorrow_info.loc[0,'holiday_rest'] !=1:
        if tomorrow_info['work'].iloc[0]==1:
            tomorrow='1'
        elif tomorrow_info['work'].iloc[0]==0:
            tomorrow='2'
    elif tomorrow_info.loc[0,'holiday_rest'] ==1:
        tomorrow='3'
        
    return tomorrow

get_tomorrow_daytype()

select holiday_today,work,holiday_rest from bmnc_stados.bmnc_date_prop t where                                                         t.date_id='20201111'

'1'

In [ ]:
import pyspark
from pyspark import SparkConf, SparkContext
#driver意思为连接spark集群的机子,所以配置host要配置当前编写代码的机子host
#conf = SparkConf().setMaster('spark://10.254.5.101:7077').set('spark.driver.host','10.254.4.106').set('spark.local.ip','10.254.4.106')
def get_spark_sess():
    conf = SparkConf().setMaster('local').setAppName('anormal_detect_compute').set('spark.executorEnv.mapreduce.job.user.name','station')
    conf.set("spark.dynamicAllocation.maxExecutors",4) #32
    sc = SparkContext.getOrCreate(conf)
    sess = pyspark.sql.SparkSession(sc)
    return sess
sess=get_spark_sess()

spark_df = sess.createDataFrame(pd_data.values.tolist(), list(pd_data.columns))

In [2]:
import os
script_path = os.path.split(os.path.realpath('__file__'))[0]
os.chdir(script_path)
import sys

from common import *

import datetime as dt
from  datetime import datetime
def start_time_format(startTime):
    start_time = datetime.strptime(compute_date+'%s:00'%startTime,'%Y%m%d%H:%M:%S')
    start_time = start_time.strftime("%Y%m%d%H%M%S")
    return start_time

def end_time_format(endTime):
    if endTime != '24:00':
        end_time = datetime.strptime(compute_date+'%s:00'%endTime,'%Y%m%d%H:%M:%S')
        end_time = (end_time+dt.timedelta(seconds=-1)).strftime("%Y%m%d%H%M%S")
    else:
        end_time = compute_date+'235959'
    return end_time

import numpy as np
import pandas as pd
from joblib import Parallel, delayed

def get_data_by_sql(date_scope,exclude_date_scope,train_date_type,train_target,train_time_size):
   
    sqlfile = '../sql/train1.sql'
    
    #节假日训练数据取双休日和节假日的历史数据合集
    if train_date_type=='3':
        sqlfile = '../sql/train3.sql'
        train_date_type="'2','3'"
            
    file = open(sqlfile,'r')
    sql_content = file.read()

    sql_train = sql_content.replace('datescope',date_scope).\
                                          replace('exclude',exclude_date_scope).\
                                          replace('work',train_date_type).\
                                          replace('target',train_target).\
                                          replace('timesize',train_time_size).\
                                          replace('\n','').split(';')
    print('train sql is: ')
    print(sql_train)
    
    for j in range(1,4):
        try:    
            for sql in sql_train:
                cur.execute(sql)
            print("success in %s times"%j)
            break

        except Exception as e:
            print(e)
            print("#######")
            print(traceback.format_exc())
            time.sleep(3)
                
    
    data = cur.fetchall()
    cols = [i[0] for i in cur.description]
    pd_data = pd.DataFrame(data,columns=cols)
    print(get_time(),'fetch over')

    return pd_data


def aggregation_data(pd_data, split_period):
    for p in split_period:
        s=p.split('-')[0]
        e=p.split('-')[1]
        pd_data.loc[(pd_data['start_tm']>=s) & (pd_data['end_tm']<=e),'newtime']= str([s,e])
    pd_data['newtime'] = pd_data[['start_tm','end_tm','newtime']].apply(lambda x: str([x['start_tm'],x['end_tm']]) if pd.isna(x['newtime']) else x['newtime'], axis=1)
    pd_data[['start_tm1','end_tm1']] = pd_data['newtime'].apply(lambda x: pd.Series(eval(x)))
    pd_data = pd_data.rename(columns={'start_tm':'start_tm2','end_tm':'end_tm2','start_tm1':'start_tm','end_tm1':'end_tm'})
    pd_data = pd_data.groupby(['line_id','station_id','start_tm','end_tm'])['qtty'].apply(','.join).reset_index()
    pd_data['qtty']=pd_data['qtty'].apply(lambda x : '[%s]'%x)
    return pd_data



def iforest_func(subset,contamination,safe_value):
    subset["detect_tmp"] = subset["qtty"].apply(lambda x:main(x,contamination,safe_value))
    return subset

def max_func(subset,safe_value):
    subset["detect_tmp"] = subset["qtty"].apply(lambda x:(max(eval(x)),max([safe_value,max(eval(x))]),np.array([])))
    return subset

import sys
def train(pd_data,algorithm_mark,alg_para_list,size,split_period):

    #计算阈值
    print(get_time(),'compute')
    pd_data_grouped = pd_data.groupby(pd_data.index)
    if len(alg_para_list)!=0:
        results = Parallel(n_jobs=30)(delayed(eval('%s_func'%algorithm_mark))(group,*alg_para_list) for name, group in pd_data_grouped)
    else:
        results = Parallel(n_jobs=30)(delayed(eval('%s_func'%algorithm_mark))(group) for name, group in pd_data_grouped)
    pd_data = pd.concat(results)  
    print(get_time(),'computed')

    #统计训练集异常明细
    print(get_time(),"statistic outliners detail")
    pd_data[['threshold','modified','outliners']]=pd_data['detect_tmp'].apply(pd.Series)
    pd_data['train_n'] = pd_data['qtty'].apply(lambda x:len(eval(x)))
    pd_data['outliner_n'] = pd_data['outliners'].apply(lambda x:len(x))
    pd_data['outliner_p'] = pd_data[['outliner_n','train_n']].apply(lambda x:'%0.5f'%(x['outliner_n']/x['train_n']),axis=1)    
    
    #检查是否有聚合，如果有聚合就还原聚合部分
    if split_period!=[]:
        print(get_time(),"revivifiction time period")   
        resplit_pd = get_splitmap_by_timesize(split_period,size=int(size))
        resplit_pd.columns=['nst','net','start_tm','end_tm']
        pd_data = pd.merge(pd_data,resplit_pd,on=['start_tm','end_tm'],how='left')
        pd_data = pd_data.rename(columns={'start_tm':'ost','end_tm':'oet','nst':'start_tm','net':'end_tm'})
        pd_data['start_tm'] = pd_data[['ost','start_tm']].apply(lambda x:x['ost'] if pd.isna(x['start_tm']) else x['start_tm'] ,axis=1)
        pd_data['end_tm'] = pd_data[['oet','end_tm']].apply(lambda x:x['oet'] if pd.isna(x['end_tm']) else x['end_tm'] ,axis=1)


    #补全时段
    print(get_time(),'add miss period')
    periods = get_period_by_timesize(int(size))
    starts = list(periods.keys())
    line_station_arr  = pd_data[['line_id','station_id']].drop_duplicates().values
    for line,station in line_station_arr:
        cur_start = pd_data.loc[pd_data['station_id']==station,'start_tm'].values
        miss_starts = list(set(starts)-set(cur_start))
        if len(miss_starts)!=0:
            for miss_start in miss_starts:
                miss_end = periods[miss_start]
                miss_list = [line,station,miss_start,miss_end,'[]',99999,99999,0,0,0.00000,'']
                rows = pd_data.shape[0]
                pd_data.loc[rows,['line_id','station_id','start_tm','end_tm','qtty','threshold','modified','train_n','outliner_n','outliner_p','outliners']]=miss_list

    pd_data['threshold'] = pd_data['threshold'].astype(int)
    pd_data['modified'] = pd_data['modified'].astype(int)
  
    print(get_time(),'complete handle %s'%size)
    
    return pd_data
    
    

        
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--train_date_scopes",type=str) #训练日期范围
parser.add_argument("--exclude_date_scopes",type=str) #过滤日期范围

parser.add_argument("--train_date_types",type=str) #训练日期类型
parser.add_argument("--train_targets",type=str) #训练指标
parser.add_argument("--train_time_sizes",type=str) #训练指标粒度


import hashlib
import traceback
import time
        

if __name__=='__main__':
     
    print('\n',get_time(),'Start Job \nset defualt parameters with config file')
    f=open('../conf/train_conf.py','r')
    for i in f:
        print(i)
    sys.path.append('../conf')
    from train_conf import *
    
    
    for j in range(1,4):
        try:    
            tomorrow_type=get_tomorrow_daytype()
            
            if train_frequency=='1':
                train_date_types=[tomorrow_type]
            elif train_frequency=='7':
                train_date_types=['1','2','3']  #训练日期类型：1工作日，2双休日，3节假日
                
            print("success in %s times"%j)
            break

        except Exception as e:
            print(e)
            print("#######")
            print(traceback.format_exc())
            train_date_types=['1','2']
            time.sleep(3)
            
    
        
    import itertools
    combinations = list(itertools.product(train_date_scopes,exclude_date_scopes,train_date_types,
                                              train_targets,train_time_sizes))

    task_n = len(combinations);count=1
    
    
    for date_scope,exclude_date_scope,train_date_type,train_target,train_time_size in combinations:
        
        data_conn,cur = get_hive_con()
        
        train_stratage = {**train_stratage_config['common'],**train_stratage_config[(train_date_type,train_target,train_time_size)]}       
        sess = get_spark_sess()
        
        print('\n',get_time(),'\n#####start training %s/%s#######'%(count,task_n))
        print( 'date_scope--%s\nexclude_date_scope--%s\
                 \ntrain_date_type--%s\ntrain_target--%s\
                 \ntrain_time_size--%s\n'% 
                 (date_scope,exclude_date_scope,train_date_type,train_target,train_time_size))
        
        
        pd_data_ori = get_data_by_sql(date_scope,exclude_date_scope,train_date_type,train_target,train_time_size)
        pd_data=pd.DataFrame([])
        for k,v in train_stratage.items():
            split_period = v[0]
            if k=='main':
                rest_key = [k for k,v in train_stratage.items() if k!='main']
                rest_key = [[i] if type(i)==str else list(i) for i in rest_key]
                if rest_key == []:
                    cur_data = pd_data_ori
                elif len(rest_key)==1:    
                    cur_data = pd_data_ori.loc[~pd_data_ori['station_id'].isin(rest_key[0])].reset_index(drop=True)
                elif len(rest_key)>1:
                    cur_data = pd_data_ori.loc[~pd_data_ori['station_id'].isin(np.sum(rest_key))].reset_index(drop=True)
            else:
                if type(k)==str:
                    k=[k]
                cur_data = pd_data_ori.loc[pd_data_ori['station_id'].isin(k)].reset_index(drop=True)

            if split_period==[]:
                train_plan_id = '1'
                cur_data['qtty']=cur_data['qtty'].apply(lambda x : '[%s]'%x)
            elif split_period!=[]:
                train_plan_id = '2'
                cur_data = aggregation_data(cur_data, split_period)            
            else:
                print("no stratage configed")

            print('\n',get_time(),k,len(cur_data),v[0],v[1],train_time_size)
            cur_data = train(cur_data,v[1][0],v[1][1:],train_time_size,split_period)
            pd_data = pd.concat([pd_data,cur_data])

        try:         
            main_stratage = train_stratage['main']
        except Exception as e:
            main_stratage = v     
        alg_with_para=",".join([str(i) for i in main_stratage[1]])
        
        if main_stratage[0]==[]:
            train_plan_id = '1'
        else:
            train_plan_id = '2'
        
        id_str = str([date_scope,exclude_date_scope,train_plan_id,train_date_type,\
               train_target,train_time_size,alg_with_para])
        md5str = hashlib.md5(id_str.encode(encoding='UTF-8')).hexdigest()
        task_id = md5str
        #插入训练任务信息表
        train_info_sql = "insert overwrite table bmnc_stados.train_his_record partition(train_id='%s') \
                                                values('%s','%s','%s','%s','%s','%s','%s','%s') \
                                    "%(task_id,get_time(),date_scope,exclude_date_scope,train_plan_id,train_date_type,\
                                       train_target,train_time_size,alg_with_para)
        print(train_info_sql)
        cur.execute(train_info_sql)
        print(get_time(),'insert train record finished')
        #pd_data['date_type'] = train_date_type
        #pd_data['train_target'] = train_target
        #pd_data['train_time_size'] = train_time_size

        pd_data = pd_data[['line_id','station_id','start_tm','end_tm','threshold','modified','train_n','outliner_n','outliner_p','outliners']]
        pd_data['outliners']=pd_data['outliners'].apply(lambda x:str(list(x)).replace('[','').replace(']',''))
        pd_data['threshold'] = pd_data['threshold'].astype(str)
        pd_data['modified'] = pd_data['modified'].astype(str)
        pd_data['train_n'] = pd_data['train_n'].astype(int).astype(str)
        pd_data['outliner_n'] = pd_data['outliner_n'].astype(int).astype(str)
        pd_data['outliner_p']=pd_data['outliner_p'].astype(str)
        
        
        spark_df = sess.createDataFrame(pd_data.values.tolist(), list(pd_data.columns))    
        hdfs_file='hdfs:/user/station/bmnc_limcp.db/train_result_detail/train_id=%s'%task_id
        print(get_time(),'Insert write to hdfs %s'%hdfs_file)
        
        for j in range(1,4):
            try:    
                spark_df.write.mode("overwrite").option("delimiter", "|").format('csv').save(hdfs_file)
                print("success in %s times"%j)
                break

            except Exception as e:
                print(e)
                print("#######")
                print(traceback.format_exc())
                time.sleep(3)
        
        print(get_time(),'hdfs file writed')
        cur.execute('msck repair table bmnc_stados.train_result_detail')
        
        count=count+1
        
        cur.close()
        data_conn.close()
        
    print("All task complete")

 2020-11-11 09:44:14 Start Job
set defualt parameters with config file
#训练任务参数



#train_data_config

train_date_scopes=['20190101-20200919'] #训练日期范围

exclude_date_scopes=['202002,202003']  #过滤日期范围



# train_targets=['entry_qtty','exit_qtty'] #训练指标： entry_qtty进站量，exit_qtty出站量

# train_time_sizes= ['0005','0015','0030','0060'] #训练粒度 ['0005','0015','0030','0060']

train_targets=['entry_qtty']

train_time_sizes= ['0060']





train_frequency='1' #训练频率：1每天训练一次 7每周训练一次



#train_stratege_config

train_stratage_config = {

    'common' : {'main':[['05:00-07:00','10:30-16:30','16:30-20:30','20:30-22:30','22:30-24:00'],['iforest',0.005,50]]}

    ,('1', 'entry_qtty', '0005') : {'main'

                                                        :[['05:00-06:30','06:30-10:00','10:00-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-06:30','10:00-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('1', 'entry_qtty', '0015') : {'main'

                                                        :[['05:00-06:30','06:30-10:00','10:00-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-06:30','10:00-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('1', 'entry_qtty', '0030')  : {'main'

                                                        :[['05:00-06:30','06:30-10:00','10:00-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-06:30','10:00-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('1', 'entry_qtty', '0060') : {'main'

                                                        :[['05:00-06:30','06:30-10:00','10:00-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-06:30','10:00-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('1', 'exit_qtty', '0005') : {'main'

                                                        :[['05:00-07:00','07:00-10:30','10:30-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:00','10:30-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('1', 'exit_qtty', '0015') : {'main'

                                                        :[['05:00-07:00','07:00-10:30','10:30-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:00','10:30-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('1', 'exit_qtty', '0030') : {'main'

                                                        :[['05:00-07:00','07:00-10:30','10:30-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:00','10:30-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('1', 'exit_qtty', '0060') : {'main'

                                                        :[['05:00-07:00','07:00-10:30','10:30-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:00','10:30-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('2', 'entry_qtty', '0005') : {'main'

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('2', 'entry_qtty', '0015') : {'main'

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('2', 'entry_qtty', '0030') : {'main'

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('2', 'entry_qtty', '0060') : {'main'

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('2', 'exit_qtty', '0005') : {'main'

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('2', 'exit_qtty', '0015') : {'main'

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('2', 'exit_qtty', '0030') : {'main'

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('2', 'exit_qtty', '0060') : {'main'

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('3', 'entry_qtty', '0005') : {'main'

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('3', 'entry_qtty', '0015') : {'main'

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('3', 'entry_qtty', '0030') : {'main'

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('3', 'entry_qtty', '0060') : {'main'

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['max',50]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-07:30','07:30-16:30','16:30-19:30','19:30-22:30','22:30-24:00'],['iforest',0.005,50]] }

    ,('3', 'exit_qtty', '0005') : {'main'

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('3', 'exit_qtty', '0015') : {'main'

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('3', 'exit_qtty', '0030') : {'main'

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }

    ,('3', 'exit_qtty', '0060') : {'main'

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['max',100]],

                                               ('0825','1531','0827','0823','0108','0735','0213','1033','0645')

                                                        :[['05:00-08:00','08:00-17:00','17:00-20:00','20:00-23:00','23:00-24:00'],['iforest',0.005,100]] }



}



"""

train_stratage_config = {

    'common' : {'main':[['05:00-07:00','10:30-16:30','16:30-20:30','20:30-22:30','22:30-24:00'],50,0.005]}

    ,('1', 'entry_qtty', '0005') : {}

    ,('1', 'entry_qtty', '0015') : {('9621','0613','0609','0104','9129','9433','9435'):[['05:00-07:00','10:30-16:30','16:30-20:30','20:30-22:30','22:30-24:00'],50,0.005]}

    ,('1', 'entry_qtty', '0030')  : {'main':[[],50,0.005],

                                               ('0103'):[['05:00-07:00','07:00-10:30','10:30-16:30','16:30-20:30','20:30-22:30','22:30-24:00'],60,0.003],

                                               ('9621','0613','0609','0104','9129','9433','9435'):[['05:00-07:00','10:30-16:30','16:30-20:30','20:30-22:30','22:30-24:00'],50,0.005]}

    ,('1', 'entry_qtty', '0060') : {}

    ,('1', 'exit_qtty', '0005') : {}

    ,('1', 'exit_qtty', '0015') : {}

    ,('1', 'exit_qtty', '0030') : {}

    ,('1', 'exit_qtty', '0060') : {}

    ,('2', 'entry_qtty', '0005') : {}

    ,('2', 'entry_qtty', '0015') : {}

    ,('2', 'entry_qtty', '0030') : {}

    ,('2', 'entry_qtty', '0060') : {}

    ,('2', 'exit_qtty', '0005') : {}

    ,('2', 'exit_qtty', '0015') : {}

    ,('2', 'exit_qtty', '0030') : {}

    ,('2', 'exit_qtty', '0060') : {}



}

"""



select holiday_today,work,holiday_rest from bmnc_stados.bmnc_date_prop t where                                                         t.date_id='20201112'

success in 1 times

 2020-11-11 09:52:15
#####start training 1/1#######
date_scope--20190101-20200919
exclude_date_scope--202002,202003
train_date_type--1
train_target--entry_qtty
train_time_size--0060

train sql is:
["select line_id,substr(station_id,-4) station_id,start_tm,regexp_replace(end_tm,'次日00:00','24:00') end_tm,entry_qtty qtty from dos_station_period_st   t where   line_id not in ('82','83','84','85','93','04') and t.start_tm >= '05:00' and t.start_tm<='23:55' and start_tm not like '%次日%'   and p_date_scope='20190101-20200919' and p_filter='202002,202003' and p_date_type_cd in ('1') and p_stat_index_type_cd='0060'"]
success in 1 times
2020-11-11 09:52:43 fetch over

 2020-11-11 09:52:43 ('0825', '1531', '0827', '0823', '0108', '0735', '0213', '1033', '0645') 108 ['05:00-06:30', '10:00-16:30', '16:30-19:30', '19:30-22:30', '22:30-24:00'] ['iforest', 0.005, 50] 0060
2020-11-11 09:52:43 compute
2020-11-11 09:52:48 computed
2020-11-11 09:52:48 statistic outliners detail
2020-11-11 09:52:48 revivifiction time period
2020-11-11 09:52:48 add miss period
2020-11-11 09:52:48 complete handle 0060

 2020-11-11 09:52:53 main 3960 ['05:00-06:30', '06:30-10:00', '10:00-16:30', '16:30-19:30', '19:30-22:30', '22:30-24:00'] ['max', 50] 0060
2020-11-11 09:52:53 compute
2020-11-11 09:53:28 computed
2020-11-11 09:53:28 statistic outliners detail
2020-11-11 09:53:36 revivifiction time period
2020-11-11 09:53:37 add miss period
2020-11-11 09:53:37 complete handle 0060
insert overwrite table bmnc_stados.train_his_record partition(train_id='5d9fd1889ebece9de6d90fdfea5c9721')                                                 values('2020-11-11 09:53:37','20190101-20200919','202002,202003','2','1','entry_qtty','0060','max,50')
2020-11-11 09:53:39 insert train record finished
2020-11-11 09:53:47 Insert write to hdfs hdfs:/user/station/bmnc_limcp.db/train_result_detail/train_id=5d9fd1889ebece9de6d90fdfea5c9721
success in 1 times
2020-11-11 09:53:51 hdfs file writed
All task complete

In [6]:
from ftplib import FTP 
import os 
import sys
sys.path.append('../conf')
from ftp_conf import *

ftp_address = '10.254.55.32'
ftp_username = 'irc_ftp'
ftp_password = '123QWEasd!@#'
ftp_dir = '/opt/irc_ftp/ftp_thr'
ftp=FTP() 

#读取配置文件的ftp参数
# ftp.set_debuglevel(2)#打开调试级别2，显示详细信息;0为关闭调试信息 
ftp.connect(ftp_address,21)#连接 
ftp.login(ftp_username,ftp_password)#登录，如果匿名登录则用空串代替即可 
print(ftp.getwelcome())#显示ftp服务器欢迎信息 
ftp.cwd(ftp_dir) #选择操作目录 



#查看文件
ftp.dir()

220 (vsFTPd 3.0.2)
-rw-r--r--    1 1003     1003           78 Nov 27 09:19 20201127072155_D053_FICC_PFW_STN_THRESHOULD5.chk
-rw-r--r--    1 1003     1003      5195046 Nov 27 09:19 20201127072155_D053_FICC_PFW_STN_THRESHOULD5.dat
-rw-r--r--    1 1003     1003           79 Nov 27 09:19 20201127072156_D054_FICC_PFW_STN_THRESHOULD15.chk
-rw-r--r--    1 1003     1003      1741522 Nov 27 09:19 20201127072156_D054_FICC_PFW_STN_THRESHOULD15.dat
-rw-r--r--    1 1003     1003           78 Nov 27 09:19 20201127072156_D055_FICC_PFW_STN_THRESHOULD30.chk
-rw-r--r--    1 1003     1003       875834 Nov 27 09:19 20201127072156_D055_FICC_PFW_STN_THRESHOULD30.dat
-rw-r--r--    1 1003     1003           77 Nov 27 09:19 20201127072156_D056_FICC_PFW_STN_THRESHOULD60.chk
-rw-r--r--    1 1003     1003       441349 Nov 27 09:19 20201127072156_D056_FICC_PFW_STN_THRESHOULD60.dat